# #######################################################################################################################################
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: front-end-ingress
  namespace: profile-site
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/limit-rps: "10"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - "*.shahsportfolio.online"
    - "kubernetes.shahsportfolio.online"
    secretName: wildcard-certificate
  rules:
    - host: kubernetes.shahsportfolio.online
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: front-end-service
              port:
                number: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: back-end-ingress
  namespace: profile-site
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/limit-rps: "10" # Limit to 10 requests per second per client IP
    # nginx.ingress.kubernetes.io/whitelist-source-range-by-header: "X-Real-IP, X-Forwarded-For"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($http_origin !~* (^https?://(k8-backend\.shahsportfolio\.online|kubernetes\.shahsportfolio\.online|shahsportfolio\.online)$)) {
        return 302 https://kubernetes.shahsportfolio.online/blocked;
      }
      add_header 'Access-Control-Allow-Origin' "$http_origin" always;
      add_header 'Access-Control-Allow-Methods' 'GET, POST, DELETE, OPTIONS' always;
      add_header 'Access-Control-Allow-Headers' 'Authorization, X-Requested-With, Content-Type' always;
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - "*.shahsportfolio.online"
    - "k8-backend.shahsportfolio.online"
    secretName: wildcard-certificate
  rules:
    - host: k8-backend.shahsportfolio.online
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: back-end-service
              port:
                number: 9000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: postgres-ingress
  namespace: profile-site
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/limit-rps: "10" # Limit to 10 requests per second per client IP
    # nginx.ingress.kubernetes.io/whitelist-source-range-by-header: "X-Real-IP, X-Forwarded-For"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($http_origin !~* (^https?://(k8-backend\.shahsportfolio\.online|kubernetes\.shahsportfolio\.online|shahsportfolio\.online)$)) {
        return 302 https://kubernetes.shahsportfolio.online/blocked;
      }
      add_header 'Access-Control-Allow-Origin' "$http_origin" always;
      add_header 'Access-Control-Allow-Methods' 'GET, POST, DELETE, OPTIONS' always;
      add_header 'Access-Control-Allow-Headers' 'Authorization, X-Requested-With, Content-Type' always;
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - "*.shahsportfolio.online"
    - "k8-db.shahsportfolio.online"
    secretName: wildcard-certificate
  rules:
    - host: k8-db.shahsportfolio.online
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: db-service
              port:
                number: 5432
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: back-end-memcache
#   namespace: profile-site
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /
#     kubernetes.io/ingress.class: nginx
#     nginx.ingress.kubernetes.io/limit-rps: "10" # Limit to 10 requests per second per client IP
#     # nginx.ingress.kubernetes.io/whitelist-source-range-by-header: "X-Real-IP, X-Forwarded-For"
#     nginx.ingress.kubernetes.io/configuration-snippet: |
#       if ($http_origin !~* (^https?://(k8-backend\.shahdevelopment\.tech|kubernetes\.shahdevelopment\.tech|shahdevelopment\.tech)$)) {
#         return 302 https://kubernetes.shahsportfolio.online/blocked;
#       }
#       add_header 'Access-Control-Allow-Origin' "$http_origin" always;
#       add_header 'Access-Control-Allow-Methods' 'GET, POST, DELETE, OPTIONS' always;
#       add_header 'Access-Control-Allow-Headers' 'Authorization, X-Requested-With, Content-Type' always;
# spec:
#   tls:
#   - hosts:
#     - "*.shahsportfolio.online"
#     secretName: wildcard-certificate
#   rules:
#     - host: k8-backend.shahsportfolio.online
#       http:
#         paths:
#         - path: /
#           pathType: Prefix
#           backend:
#             service:
#               name: back-end-service
#               port:
#                 number: 9000
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: back-end-rabbit
#   namespace: profile-site
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /
#     kubernetes.io/ingress.class: nginx
#     nginx.ingress.kubernetes.io/limit-rps: "10" # Limit to 10 requests per second per client IP
#     # nginx.ingress.kubernetes.io/whitelist-source-range-by-header: "X-Real-IP, X-Forwarded-For"
#     nginx.ingress.kubernetes.io/configuration-snippet: |
#       if ($http_origin !~* (^https?://(k8-backend\.shahdevelopment\.tech|kubernetes\.shahdevelopment\.tech|shahdevelopment\.tech)$)) {
#         return 302 https://kubernetes.shahsportfolio.online/blocked;
#       }
#       add_header 'Access-Control-Allow-Origin' "$http_origin" always;
#       add_header 'Access-Control-Allow-Methods' 'GET, POST, DELETE, OPTIONS' always;
#       add_header 'Access-Control-Allow-Headers' 'Authorization, X-Requested-With, Content-Type' always;
# spec:
#   tls:
#   - hosts:
#     - "*.shahsportfolio.online"
#     secretName: wildcard-certificate
#   rules:
#     - host: k8-rabbit.shahsportfolio.online
#       http:
#         paths:
#         - path: /
#           pathType: Prefix
#           backend:
#             service:
#               name: back-end-service
#               port:
#                 number: 9000
# #######################################################################################################################################
# #######################################################################################################################################