apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-pv
  namespace: profile-site
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2
  awsElasticBlockStore:
    volumeID: {{.Values.ebsId}}  # Replace with your EBS Volume ID
    fsType: ext4