apiVersion: v1
kind: PersistentVolume
metadata:
  name: s3-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: s3-storage
  mountOptions:
    - use_path_request_style
  awsS3:
    bucket: s3://kubedevops001
    prefix: /kube_pv
    # region: us-east-1 (optional)