# #######################################################################################################################################
# #######################################################################################################################################
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-tiger-docker
  namespace: profile-site
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{.Values.docker_configjson}}
# #######################################################################################################################################
---
apiVersion: v1
kind: Secret
metadata:
  name: wildcard-certificate
  namespace: profile-site
type: kubernetes.io/tls
data:
  tls.crt: {{.Values.tls_crt}}
  tls.key: {{.Values.tls_key}}
# #######################################################################################################################################
---
apiVersion: v1
kind: Secret
metadata:
  name: wildcard-certificate
  namespace: ingress-nginx
type: kubernetes.io/tls
data:
  tls.crt: {{.Values.tls_crt}}
  tls.key: {{.Values.tls_key}}
# #######################################################################################################################################
# #######################################################################################################################################
---
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-basic-auth
  namespace: ingress-nginx
type: Opaque
data:
  .htpasswd: {{.Values.ht_pass}}
---
apiVersion: v1
kind: Secret
metadata:
  name: my-ca-secret
  namespace: profile-site  # Replace with your namespace if needed
type: Opaque
data:
  ca.crt: {{.Values.ca_crt}}
---
apiVersion: v1
kind: Secret
metadata:
  name: my-client-secret
  namespace: profile-site  # Replace with your namespace if needed
type: Opaque
data:
  prometheus.crt: {{.Values.client_cert}}
---
apiVersion: v1
kind: Secret
metadata:
  name: my-key-secret
  namespace: profile-site  # Replace with your namespace if needed
type: Opaque
data:
  prometheus.key: {{.Values.client_key}}