# #######################################################################################################################################
# #######################################################################################################################################
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-tiger-docker
  namespace: profile-site
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{.Values.docker_configjson}}
# #######################################################################################################################################
---
apiVersion: v1
kind: Secret
metadata:
  name: wildcard-certificate
  namespace: profile-site
type: kubernetes.io/tls
data:
  tls.crt: {{.Values.tls_crt}}
  tls.key: {{.Values.tls_key}}
# #######################################################################################################################################
---
apiVersion: v1
kind: Secret
metadata:
  name: wildcard-certificate
  namespace: ingress-nginx
type: kubernetes.io/tls
data:
  tls.crt: {{.Values.tls_crt}}
  tls.key: {{.Values.tls_key}}
# #######################################################################################################################################
# #######################################################################################################################################
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-basic-auth
  namespace: ingress-nginx
type: Opaque
data:
  .htpasswd: {{.Values.ht_pass}}